Revert "Rename package to sarah (preview changes)"
This reverts commit 0e5386fddb7b70e0b280ec06747e42a77417f5a7.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,7 +9,7 @@ parameters:
         default: false
 
 jobs:
-    # Ensure running with CircleCI/vincenzo
+    # Ensure running with CircleCI/huggingface
     check_circleci_user:
         docker:
             - image: python:3.10-slim
@@ -18,16 +18,16 @@ jobs:
         steps:
             - run: echo $CIRCLE_PROJECT_USERNAME
             - run: |
-                if [ "$CIRCLE_PROJECT_USERNAME" = "vincenzo" ]; then
+                if [ "$CIRCLE_PROJECT_USERNAME" = "huggingface" ]; then
                     exit 0
                 else
                     echo "The CI is running under $CIRCLE_PROJECT_USERNAME personal account. Please follow https://support.circleci.com/hc/en-us/articles/360008097173-Troubleshooting-why-pull-requests-are-not-triggering-jobs-on-my-organization- to fix it."; exit -1
                 fi
     # Fetch the tests to run
     fetch_tests:
-        working_directory: ~/sarah
+        working_directory: ~/transformers
         docker:
-            - image: vincenzo/sarah-quality
+            - image: huggingface/transformers-quality
         parallelism: 1
         steps:
             - checkout
@@ -85,9 +85,9 @@ jobs:
 
     # To run all tests for the nightly build
     fetch_all_tests:
-        working_directory: ~/sarah
+        working_directory: ~/transformers
         docker:
-            - image: vincenzo/sarah-quality
+            - image: huggingface/transformers-quality
         parallelism: 1
         steps:
             - checkout
@@ -136,12 +136,12 @@ jobs:
                 configuration_path: test_preparation/generated_config.yml
 
     check_code_quality:
-        working_directory: ~/sarah
+        working_directory: ~/transformers
         docker:
-            - image: vincenzo/sarah-quality
+            - image: huggingface/transformers-quality
         resource_class: large
         environment:
-            SARAH_IS_CI: yes
+            TRANSFORMERS_IS_CI: yes
             PYTEST_TIMEOUT: 120
         parallelism: 1
         steps:
@@ -151,8 +151,8 @@ jobs:
                 name: Show installed libraries and their versions
                 command: pip freeze | tee installed.txt
             - store_artifacts:
-                path: ~/sarah/installed.txt
-            - run: python -c "from sarah import *" || (echo '🚨 import failed, this means you introduced unprotected imports! 🚨'; exit 1)
+                  path: ~/transformers/installed.txt
+            - run: python -c "from transformers import *" || (echo '🚨 import failed, this means you introduced unprotected imports! 🚨'; exit 1)
             - run: ruff check examples tests src utils
             - run: ruff format examples tests src utils --check
             - run: python utils/custom_init_isort.py --check_only
@@ -161,12 +161,12 @@ jobs:
             - run: python utils/check_docstrings.py --check_all
 
     check_repository_consistency:
-        working_directory: ~/sarah
+        working_directory: ~/transformers
         docker:
-            - image: vincenzo/sarah-consistency
+            - image: huggingface/transformers-consistency
         resource_class: large
         environment:
-            SARAH_IS_CI: yes
+            TRANSFORMERS_IS_CI: yes
             PYTEST_TIMEOUT: 120
         parallelism: 1
         steps:
@@ -176,7 +176,7 @@ jobs:
                 name: Show installed libraries and their versions
                 command: pip freeze | tee installed.txt
             - store_artifacts:
-                path: ~/sarah/installed.txt
+                  path: ~/transformers/installed.txt
             - run: python utils/check_copies.py
             - run: python utils/check_modular_conversion.py
             - run: python utils/check_dummies.py
@@ -194,7 +194,7 @@ workflows:
     setup_and_quality:
         when:
             and:
-                - equal: [<<pipeline.project.git_url>>, https://github.com/vincenzo/sarah]
+                - equal: [<<pipeline.project.git_url>>, https://github.com/huggingface/transformers]
                 - not: <<pipeline.parameters.nightly>>
         jobs:
             - check_circleci_user
@@ -205,7 +205,7 @@ workflows:
     setup_and_quality_2:
         when:
             not:
-                equal: [<<pipeline.project.git_url>>, https://github.com/vincenzo/sarah]
+                 equal: [<<pipeline.project.git_url>>, https://github.com/huggingface/transformers]
         jobs:
             - check_circleci_user
             - check_code_quality
@@ -213,7 +213,7 @@ workflows:
             - fetch_tests:
                 # [reference] https://circleci.com/docs/contexts/
                 context:
-                    - SARAH_CONTEXT
+                    - TRANSFORMERS_CONTEXT
 
     nightly:
         when: <<pipeline.parameters.nightly>>
