clean-up

diff --git a/.github/workflows/add-model-like.yml b/.github/workflows/add-model-like.yml
--- a/.github/workflows/add-model-like.yml
+++ b/.github/workflows/add-model-like.yml
@@ -30,11 +30,22 @@ jobs:
           key: v2-tests_model_like-${{ hashFiles('setup.py') }}
 
       - name: Create virtual environment on cache miss
-        if: steps.cache.outputs.cache-hit != 'false'
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
           python -m venv ~/venv && . ~/venv/bin/activate
           pip install --upgrade pip!=21.3
           pip install -e .[dev]
+
+      - name: Check transformers location
+        run: |
+          . ~/venv/bin/activate
+          transformer_loc=$(pip show transformers | grep "Location: " | cut -c11-)
+          transformer_repo_loc=$(pwd .)
+          if [ "$transformer_loc" != "$transformer_repo_loc/src" ]; then
+              echo "transformers is from $transformer_loc but it shoud be from $transformer_repo_loc/src."
+              echo "A fix is required. Stop testing."
+              exit 1
+          fi
 
       - name: Create model files
         run: |
