add check

diff --git a/.github/workflows/model-templates.yml b/.github/workflows/model-templates.yml
--- a/.github/workflows/model-templates.yml
+++ b/.github/workflows/model-templates.yml
@@ -42,6 +42,16 @@ jobs:
           pip install --upgrade pip!=21.3
           pip install -e .[dev]
 
+      - name: Check transformers location
+        run: |
+          transformer_loc=$(pip show transformers | grep "Location: " | cut -c11-)
+          transformer_repo_loc=$(pwd .)
+          if [ "$transformer_loc" == "$transformer_repo_loc/src" ]; then
+              echo "transformers is from $transformer_loc but it shoud be from $transformer_repo_loc/src."
+              echo "A fix is required. Stop testing."
+              exit 1
+          fi
+
       - name: Create model files
         run: |
           . ~/venv/bin/activate
