tentative

diff --git a/.github/workflows/self-pr-slow-ci.yml b/.github/workflows/self-pr-slow-ci.yml
--- a/.github/workflows/self-pr-slow-ci.yml
+++ b/.github/workflows/self-pr-slow-ci.yml
@@ -5,6 +5,8 @@ on:
     paths:
       - "src/transformers/models/*/modeling_*.py"
       - "tests/**/test_*.py"
+  issue_comment:
+    types: [created]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
@@ -29,7 +31,7 @@ jobs:
       runs-on: ubuntu-22.04
       name: Find models to run slow tests
       # Triggered only if the required label `run-slow` is added
-      if: ${{ contains(github.event.pull_request.labels.*.name, 'run-slow') }}
+      if: ${{ contains(github.event.pull_request.labels.*.name, 'run-slow') }} || github.event.comment.body.startsWith('/run-tests') }}
       outputs:
         models: ${{ steps.models_to_run.outputs.models }}
       steps:
@@ -41,6 +43,15 @@ jobs:
         - name: Get commit message
           run: |
             echo "commit_message=$(git show -s --format=%s)" >> $GITHUB_ENV
+
+      - name: Parse comment and set machine type
+        if: github.event_name == 'issue_comment'
+        run: |
+          COMMENT=${{ github.event.comment.body }}
+          if [[ "$COMMENT" == *"--device"* ]]; then
+            DEVICE=$(echo "$COMMENT" | grep -oP '(?<=--device\s)\S+')
+            echo "machine_type=${DEVICE}" >> $GITHUB_OUTPUT
+          fi
 
         - name: Get models to run slow tests
           run: |
@@ -56,30 +67,42 @@ jobs:
             echo "models=${{ env.models }}" >> $GITHUB_OUTPUT
 
   run_models_gpu:
-      name: Run all tests for the model
-      # Triggered only `find_models_to_run` is triggered (label `run-slow` is added) which gives the models to run
-      # (either a new model PR or via a commit message)
-      if: ${{ needs.find_models_to_run.outputs.models != '[]' }}
-      needs: find_models_to_run
-      strategy:
-        fail-fast: false
-        matrix:
-          folders: ${{ fromJson(needs.find_models_to_run.outputs.models) }}
-          machine_type: [single-gpu, multi-gpu]
-      runs-on: ['${{ matrix.machine_type }}', nvidia-gpu, t4, ci]
-      container:
-        image: huggingface/transformers-all-latest-gpu
-        options: --gpus all --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
-      steps:
+    name: Run all tests for the model
+    if: ${{ needs.find_models_to_run.outputs.models != '[]' || github.event_name == 'issue_comment' }}
+    needs: find_models_to_run
+    strategy:
+      fail-fast: false
+      matrix:
+        folders: ${{ fromJson(needs.find_models_to_run.outputs.models) || '[]' }}
+        machine_type: [single-gpu, multi-gpu]
+    runs-on: ['${{ matrix.machine_type }}', nvidia-gpu, t4, ci]
+    container:
+      image: huggingface/transformers-all-latest-gpu
+      options: --gpus all --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
+    steps:
+      - name: Parse command from PR comment
+        if: ${{ github.event_name == 'issue_comment' }}
+        id: parse_command
+        run: |
+          comment="${{ github.event.comment.body }}"
+          if [[ "$comment" =~ /run[[:space:]]+pytest ]]; then
+            export pytest_command=$(echo "$comment" | sed -n 's/\/run[[:space:]]\+pytest[[:space:]]\+\(.*\)/\1/p')
+            echo "pytest_command=$pytest_command" >> $GITHUB_ENV
+          else
+            echo "Invalid command. Exiting."
+            exit 1
+        env:
+          pytest_command: ""
+
       - name: Echo input and matrix info
+        if: ${{ github.event_name == 'pull_request' || env.pytest_command != '' }}
         shell: bash
         run: |
           echo "${{ matrix.folders }}"
 
       - name: Echo folder ${{ matrix.folders }}
+        if: ${{ github.event_name == 'pull_request' || env.pytest_command != '' }}
         shell: bash
-        # For folders like `models/bert`, set an env. var. (`matrix_folders`) to `models_bert`, which will be used to
-        # set the artifact folder names (because the character `/` is not allowed).
         run: |
           echo "${{ matrix.folders }}"
           matrix_folders=${{ matrix.folders }}
@@ -114,6 +137,16 @@ jobs:
           export CUDA_VISIBLE_DEVICES="$(python3 utils/set_cuda_devices_for_ci.py --test_folder ${{ matrix.folders }})"
           echo $CUDA_VISIBLE_DEVICES
           python3 -m pytest -v -rsfE --make-reports=${{ matrix.machine_type }}_run_models_gpu_${{ matrix.folders }}_test_reports tests/${{ matrix.folders }}
+
+
+      - name: Run custom tests from comment
+        working-directory: /transformers
+        if: ${{ github.event_name == 'issue_comment' && env.pytest_command != '' }}
+        run: |
+          export CUDA_VISIBLE_DEVICES="$(python3 utils/set_cuda_devices_for_ci.py)"
+          echo $CUDA_VISIBLE_DEVICES
+          python3 -m pytest -v ${{ env.pytest_command }}
+
 
       - name: Failure short reports
         if: ${{ failure() }}
